[package]
name = "transactions"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.10"  # Ensure this matches the version you're using
solana-client = "1.10" # Solana client for sending transactions
tokio = { version = "1", features = ["full"] }